"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_entities', 'alerts', ['entities'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_alerts_rule'), 'alerts', ['rule'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=200), nullable=True),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_ts', 'audit_log', ['action', 'ts'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_audit_object', 'audit_log', ['object_type', 'object_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deletion_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_requests_entity_id'), 'deletion_requests', ['entity_id'], unique=False)
    op.create_geospatial_table('entities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('epistemic_status', sa.String(length=32), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('geom', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('merged_into', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_entities_geom', 'entities', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_entities_merged_into'), 'entities', ['merged_into'], unique=False)
    op.create_index(op.f('ix_entities_observed_at'), 'entities', ['observed_at'], unique=False)
    op.create_index('ix_entities_properties', 'entities', ['properties'], unique=False, postgresql_using='gin', postgresql_ops={'properties': 'jsonb_path_ops'})
    op.create_index('ix_entities_search_trgm', 'entities', ['search_text'], unique=False, postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.create_index('ix_entities_source_ids', 'entities', ['source_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_index('ix_entities_type_label', 'entities', ['type', 'label'], unique=False)
    op.create_geospatial_table('events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entity_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=True),
    sa.Column('geom', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('epistemic_status', sa.String(length=32), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_events_geom', 'events', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_events_entity_ids', 'events', ['entity_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_events_location_id'), 'events', ['location_id'], unique=False)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index(op.f('ix_events_source_record_id'), 'events', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index('ix_events_type_ts', 'events', ['event_type', 'timestamp'], unique=False)
    op.create_geospatial_table('geofences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('geom', Geography(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_geofences_geom', 'geofences', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('investigations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collaborators', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineage_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('child_kind', sa.String(length=32), nullable=False),
    sa.Column('child_id', sa.String(length=64), nullable=False),
    sa.Column('parent_kind', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=False),
    sa.Column('transformation', sa.String(length=128), nullable=False),
    sa.Column('transformation_version', sa.String(length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lineage_child', 'lineage_links', ['child_kind', 'child_id'], unique=False)
    op.create_index('ix_lineage_parent', 'lineage_links', ['parent_kind', 'parent_id'], unique=False)
    op.create_table('resolution_candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_a', sa.String(length=64), nullable=False),
    sa.Column('entity_b', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('resolver_version', sa.String(length=32), nullable=False),
    sa.Column('merged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_a', 'entity_b', name='uq_resolution_pair')
    )
    op.create_index(op.f('ix_resolution_candidates_decision'), 'resolution_candidates', ['decision'], unique=False)
    op.create_index(op.f('ix_resolution_candidates_entity_a'), 'resolution_candidates', ['entity_a'], unique=False)
    op.create_index(op.f('ix_resolution_candidates_entity_b'), 'resolution_candidates', ['entity_b'], unique=False)
    op.create_index(op.f('ix_resolution_candidates_entity_type'), 'resolution_candidates', ['entity_type'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('entity_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('epistemic_status', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index('ix_signals_entity_ids', 'signals', ['entity_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_signals_rule_id'), 'signals', ['rule_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assertions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=True),
    sa.Column('subject_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('analyst_confidence', sa.String(length=32), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('epistemic_status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assertions_investigation_id'), 'assertions', ['investigation_id'], unique=False)
    op.create_table('entity_identifiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'kind', 'value', name='uq_identifier')
    )
    op.create_index(op.f('ix_entity_identifiers_entity_id'), 'entity_identifiers', ['entity_id'], unique=False)
    op.create_index('ix_identifiers_kind_value', 'entity_identifiers', ['kind', 'value'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('transformation_version', sa.String(length=32), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    op.create_table('investigation_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('epistemic_status', sa.String(length=32), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_items_inv_kind', 'investigation_items', ['investigation_id', 'kind'], unique=False)
    op.create_index(op.f('ix_investigation_items_investigation_id'), 'investigation_items', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_items_ref_id'), 'investigation_items', ['ref_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('epistemic_status', sa.String(length=32), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_records', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analyst_modifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rel_source_records', 'relationships', ['source_records'], unique=False, postgresql_using='gin')
    op.create_index('ix_rel_source_type', 'relationships', ['source_id', 'type'], unique=False)
    op.create_index('ix_rel_target_type', 'relationships', ['target_id', 'type'], unique=False)
    op.create_index(op.f('ix_relationships_timestamp'), 'relationships', ['timestamp'], unique=False)
    op.create_index(op.f('ix_relationships_type'), 'relationships', ['type'], unique=False)
    op.create_table('saved_queries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('query_kind', sa.String(length=32), nullable=False),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=200), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transformation_version', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_record_id', name='uq_source_record')
    )
    op.create_index(op.f('ix_source_records_ingestion_run_id'), 'source_records', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_source_records_record_type'), 'source_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_source_records_source_id'), 'source_records', ['source_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_source_records_source_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_record_type'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_ingestion_run_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_table('saved_queries')
    op.drop_index(op.f('ix_relationships_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_timestamp'), table_name='relationships')
    op.drop_index('ix_rel_target_type', table_name='relationships')
    op.drop_index('ix_rel_source_type', table_name='relationships')
    op.drop_index('ix_rel_source_records', table_name='relationships', postgresql_using='gin')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_investigation_items_ref_id'), table_name='investigation_items')
    op.drop_index(op.f('ix_investigation_items_investigation_id'), table_name='investigation_items')
    op.drop_index('ix_inv_items_inv_kind', table_name='investigation_items')
    op.drop_table('investigation_items')
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('ix_identifiers_kind_value', table_name='entity_identifiers')
    op.drop_index(op.f('ix_entity_identifiers_entity_id'), table_name='entity_identifiers')
    op.drop_table('entity_identifiers')
    op.drop_index(op.f('ix_assertions_investigation_id'), table_name='assertions')
    op.drop_table('assertions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_signals_rule_id'), table_name='signals')
    op.drop_index('ix_signals_entity_ids', table_name='signals', postgresql_using='gin')
    op.drop_table('signals')
    op.drop_table('rules')
    op.drop_index(op.f('ix_resolution_candidates_entity_type'), table_name='resolution_candidates')
    op.drop_index(op.f('ix_resolution_candidates_entity_b'), table_name='resolution_candidates')
    op.drop_index(op.f('ix_resolution_candidates_entity_a'), table_name='resolution_candidates')
    op.drop_index(op.f('ix_resolution_candidates_decision'), table_name='resolution_candidates')
    op.drop_table('resolution_candidates')
    op.drop_index('ix_lineage_parent', table_name='lineage_links')
    op.drop_index('ix_lineage_child', table_name='lineage_links')
    op.drop_table('lineage_links')
    op.drop_table('investigations')
    op.drop_geospatial_index('idx_geofences_geom', table_name='geofences', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('geofences')
    op.drop_index('ix_events_type_ts', table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_source_record_id'), table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_location_id'), table_name='events')
    op.drop_index('ix_events_entity_ids', table_name='events', postgresql_using='gin')
    op.drop_geospatial_index('idx_events_geom', table_name='events', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('events')
    op.drop_index('ix_entities_type_label', table_name='entities')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index('ix_entities_source_ids', table_name='entities', postgresql_using='gin')
    op.drop_index('ix_entities_search_trgm', table_name='entities', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.drop_index('ix_entities_properties', table_name='entities', postgresql_using='gin', postgresql_ops={'properties': 'jsonb_path_ops'})
    op.drop_index(op.f('ix_entities_observed_at'), table_name='entities')
    op.drop_index(op.f('ix_entities_merged_into'), table_name='entities')
    op.drop_geospatial_index('idx_entities_geom', table_name='entities', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('entities')
    op.drop_index(op.f('ix_deletion_requests_entity_id'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_table('data_sources')
    op.drop_index('ix_audit_object', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index('ix_audit_action_ts', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule'), table_name='alerts')
    op.drop_index('ix_alerts_entities', table_name='alerts', postgresql_using='gin')
    op.drop_table('alerts')
    # ### end Alembic commands ###
