"""One-off helper that writes data/schemas/ontology.json (kept for reproducibility)."""
import json, pathlib

P = lambda t="string", **kw: {"type": t, **kw}
ANY = ["*"]
entity_types = {
  "Person": {"label": "name", "description": "A natural person (synthetic in demo data).",
    "properties": {"name": P(searchable=True, sensitivity="pii", resolution="name"),
                   "email": P(identifier="email", sensitivity="pii", searchable=True, resolution="email"),
                   "phone": P(identifier="phone", sensitivity="pii", searchable=True, resolution="phone"),
                   "date_of_birth": P("date", sensitivity="restricted", resolution="dob"),
                   "address": P(sensitivity="pii", resolution="address"),
                   "national_id": P(identifier="national_id", sensitivity="restricted"),
                   "nationality": P(), "occupation": P()}},
  "Organization": {"label": "name", "description": "Company, NGO, agency or other legal body.",
    "properties": {"name": P(searchable=True, resolution="org_name"),
                   "registration_number": P(identifier="org_reg", searchable=True, resolution="org_reg"),
                   "jurisdiction": P(), "industry": P(), "address": P(resolution="address")}},
  "Account": {"label": "account_number", "description": "Financial or service account.",
    "properties": {"account_number": P(identifier="account", searchable=True, sensitivity="pii"),
                   "account_type": P(), "currency": P(), "opened_at": P("datetime"),
                   "status": P(), "balance": P("number", sensitivity="restricted")}},
  "Device": {"label": "device_id", "description": "Physical or virtual device.",
    "properties": {"device_id": P(identifier="device", searchable=True), "device_type": P(),
                   "os": P(), "fingerprint": P(identifier="device_fp")}},
  "Transaction": {"label": "transaction_id", "description": "A financial transaction.",
    "properties": {"transaction_id": P(identifier="transaction", searchable=True), "amount": P("number"),
                   "currency": P(), "channel": P(), "timestamp": P("datetime"), "status": P()}},
  "Location": {"label": "name", "description": "A named place with coordinates.",
    "properties": {"name": P(searchable=True), "city": P(searchable=True), "country": P(),
                   "lat": P("number"), "lon": P("number"), "category": P()}},
  "Address": {"label": "line1", "description": "Postal address.",
    "properties": {"line1": P(searchable=True, sensitivity="pii"), "city": P(), "postcode": P(), "country": P()}},
  "IPAddress": {"label": "ip", "description": "IPv4/IPv6 address.",
    "properties": {"ip": P(identifier="ip", searchable=True), "asn": P(), "country": P()}},
  "Domain": {"label": "domain", "description": "DNS domain name.",
    "properties": {"domain": P(identifier="domain", searchable=True), "registrar": P(), "created": P("date")}},
  "Vehicle": {"label": "plate", "description": "Road vehicle.",
    "properties": {"plate": P(identifier="plate", searchable=True, sensitivity="pii"), "make": P(), "model": P()}},
  "Shipment": {"label": "shipment_id", "description": "A consignment of goods.",
    "properties": {"shipment_id": P(identifier="shipment", searchable=True), "product": P(searchable=True),
                   "quantity": P("number"), "status": P(), "origin": P(), "destination": P()}},
  "Vessel": {"label": "name", "description": "A ship.",
    "properties": {"name": P(searchable=True), "imo": P(identifier="imo", searchable=True), "flag": P()}},
  "Event": {"label": "title", "description": "A discrete happening that is itself analysed as an entity.",
    "properties": {"title": P(searchable=True), "event_type": P(), "timestamp": P("datetime")}},
  "Document": {"label": "title", "description": "A document or file.",
    "properties": {"title": P(searchable=True), "doc_type": P(), "sha256": P(identifier="sha256")}},
  "Case": {"label": "title", "description": "An external case reference.",
    "properties": {"title": P(searchable=True), "reference": P(identifier="case_ref", searchable=True)}},
}
R = lambda desc, s=ANY, t=ANY, **kw: {"description": desc, "source_types": s, "target_types": t, **kw}
relationship_types = {
  "OWNS": R("Source owns/holds target.", ["Person", "Organization"], ["Account", "Device", "Vehicle", "Vessel", "Domain", "Organization"]),
  "WORKS_FOR": R("Person works for organisation.", ["Person"], ["Organization"]),
  "EMPLOYED_BY": R("Employment (HR-sourced).", ["Person"], ["Organization"]),
  "CONTROLS": R("Beneficial / effective control.", ["Person", "Organization"], ["Organization", "Account"]),
  "INITIATED": R("Account initiated a transaction.", ["Account"], ["Transaction"]),
  "TRANSFERRED_TO": R("Value moved to target.", ["Transaction", "Account"], ["Account", "Organization"]),
  "TRANSACTED_WITH": R("Aggregated trading relationship.", ["Account", "Person", "Organization"], ["Account", "Person", "Organization"], symmetric=True),
  "LOCATED_AT": R("Entity located at place.", ANY, ["Location", "Address"]),
  "REGISTERED_AT": R("Registered address.", ["Organization", "Person", "Vessel", "Vehicle"], ["Address", "Location"]),
  "CONNECTED_TO": R("Network connection.", ["Device", "IPAddress", "Account"], ["IPAddress", "Domain", "Device"]),
  "USED": R("Entity used a device.", ["Account", "Person"], ["Device"]),
  "COMMUNICATED_WITH": R("Communication.", ["Person", "Device", "Organization"], ["Person", "Device", "Organization"], symmetric=True),
  "VISITED": R("Entity was at a location.", ["Person", "Device", "Vehicle", "Vessel"], ["Location"]),
  "RESOLVES_TO": R("DNS resolution.", ["Domain"], ["IPAddress"]),
  "SHIPPED_BY": R("Shipment sent by supplier.", ["Shipment"], ["Organization"]),
  "SHIPPED_TO": R("Shipment destination party.", ["Shipment"], ["Organization"]),
  "CARRIED_BY": R("Shipment carried by vessel/vehicle.", ["Shipment"], ["Vessel", "Vehicle"]),
  "PASSED_THROUGH": R("Shipment/vessel passed through location.", ["Shipment", "Vessel"], ["Location"]),
  "ASSOCIATED_WITH": R("Generic association.", ANY, ANY, symmetric=True),
  "DERIVED_FROM": R("Derivation lineage between entities.", ANY, ANY),
  "MENTIONS": R("Document mentions entity.", ["Document"], ANY),
  "PART_OF": R("Membership.", ANY, ["Case", "Organization"]),
}
onto = {
  "version": "1.0.0",
  "name": "tessera-core",
  "description": "Configurable core ontology. Edit this file (or POST /api/ontology as ADMIN) to extend.",
  "sensitivity_levels": {"public": "Visible to all roles", "pii": "Personal data: masked for VIEWER", "restricted": "Highly sensitive: ADMIN/INVESTIGATOR only"},
  "entity_types": entity_types,
  "relationship_types": relationship_types,
  "event_types": ["login", "logout", "auth_failure", "transaction", "device_connection", "location_change",
                   "shipment_departure", "shipment_arrival", "port_call", "alert", "incident", "communication",
                   "process_start", "dns_query", "account_opened", "maintenance"],
}
out = pathlib.Path(__file__).resolve().parents[1] / "data" / "schemas" / "ontology.json"
out.write_text(json.dumps(onto, indent=2))
print("wrote", out)
